name: personalized_news_aggregator
description: Personalized News Aggregator - Flutter (Dart) example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.3.6

  # HTTP
  dio: ^5.2.2
  flutter_dotenv: ^5.0.2

  # Local cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.1.1

  # UX
  cached_network_image: ^3.2.3
  flutter_staggered_animations: ^1.1.0
  pull_to_refresh: ^2.0.0

  # Webview & share
  webview_flutter: ^4.0.7
  share_plus: ^6.3.0

  # Utilities
  connectivity_plus: ^4.0.1
  intl: ^0.18.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  win32: ^3.1.4
